---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: end-of-file-fixer
          - id: double-quote-string-fixer
          - id: trailing-whitespace
          - id: name-tests-test
          - id: mixed-line-ending
          - id: end-of-file-fixer
          - id: check-toml
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.2
      hooks:
          - id: yamlfmt
            name: format yaml files
    - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
      rev: v9.1.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
            additional_dependencies: ['@commitlint/config-angular']
    - repo: local
      hooks:
          - id: pytest
            name: pytest
            entry: pytest
            language: system
            types: [python]
            require_serial: true
            pass_filenames: false
            always_run: true
            args:
                - project
                - -vv
          - id: mypy
            name: mypy
            entry: mypy
            language: system
            types: [python]
            require_serial: true
            pass_filenames: false
            always_run: true
            args:
                - project
                - --install-types
                - --non-interactive
